const data = [
  {
    weight: "20KG",
    country: "Brazil",
    brand: "Frimesa",
    product: "Pork Ribs",
    price: 15.8,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "10KG",
    country: "Brazil",
    brand: "Tonnies",
    product: "Packaged Pork Ribs",
    price: 13,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Brazil",
    brand: "Palmali",
    product: "Pork Shoulder",
    price: 9.9,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Brazil",
    brand: "Pamplona",
    product: "Pork Shoulder",
    price: 9.9,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "25KG*",
    country: "Brazil",
    brand: "Frimesa",
    product: "Pork Shoulder",
    price: 10.2,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "20KG",
    country: "Germany",
    brand: "Westfleisch",
    product: "Pork Loin Fat",
    price: 7.4,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Spain",
    brand: "Artigas Duroc",
    product: "Pork French Cut",
    price: 39,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Spain",
    brand: "Pernam Ibericos",
    product: "Pork Backbone",
    price: 58,
    unit: "KG",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Spain",
    brand: "Jamondul Ibericos",
    product: "Pork Tenderloin",
    price: 167,
    unit: "KG",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Spain",
    brand: "Jamondul Ibericos",
    product: "Pork Loin",
    price: 122,
    unit: "KG",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Spain",
    brand: "Jamondul Ibericos",
    product: "Pork French Cut",
    price: 167,
    unit: "KG",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Spain",
    brand: "Jamondul Ibericos",
    product: "Pork Ribs",
    price: 122,
    unit: "KG",
    currency: "USD",
  },
  {
    weight: "15KG",
    country: "Brazil",
    brand: "Sulita",
    product: "Pork Ears",
    price: 10,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "15KG",
    country: "Brazil",
    brand: "Alibem",
    product: "Pork Stomach",
    price: 10,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "18KG",
    country: "Brazil",
    brand: "Frimesa",
    product: "Pork Stomach",
    price: 12.2,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "18KG",
    country: "Brazil",
    brand: "Frimesa",
    product: "Pork Tongue",
    price: 7,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "20KG",
    country: "Brazil",
    brand: "Frimesa",
    product: "Pork Knuckle",
    price: 5.6,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "18KG",
    country: "Brazil",
    brand: "Seara",
    product: "Pork Knuckle",
    price: 4.5,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "Copy",
    country: "Brazil",
    brand: "Alegra",
    product: "Pork Shanks (0.8-1KG)",
    price: 8.8,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "15KG",
    country: "Denmark",
    brand: "Tican",
    product: "Pork Shanks",
    price: 8.2,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "20KG",
    country: "Poland",
    brand: "Animex",
    product: "Pork Neck Bones",
    price: 5.1,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "20KG",
    country: "Poland",
    brand: "Pork Back Bones PL30251102",
    product: "Pork Back Bones",
    price: 3.2,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "20KG",
    country: "Poland",
    brand: "Pork Front Bones PL30251102",
    product: "Pork Front Bones",
    price: 3.2,
    unit: "lb",
    currency: "USD",
  },
  {
    weight: "10KG",
    country: "Poland",
    brand: "Aurora",
    product: "Pork Belly Strips",
    price: 14,
    unit: "lb",
    currency: "USD",
  },
];

export default data;
